# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/omnisense/common/proto/map.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common.proto import header_pb2 as modules_dot_common_dot_proto_dot_header__pb2
from modules.omnisense.common.proto import pose_pb2 as modules_dot_omnisense_dot_common_dot_proto_dot_pose__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/omnisense/common/proto/map.proto',
  package='omnisense.map.proto',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(modules/omnisense/common/proto/map.proto\x12\x13omnisense.map.proto\x1a!modules/common/proto/header.proto\x1a)modules/omnisense/common/proto/pose.proto\"\xb3\x01\n\rJoinPointPair\x12\x36\n\nnear_point\x18\x01 \x01(\x0b\x32\".omnisense.drivers.seyond.PointENU\x12\x35\n\tfar_point\x18\x02 \x01(\x0b\x32\".omnisense.drivers.seyond.PointENU\x12\x33\n\x08position\x18\x03 \x01(\x0e\x32!.omnisense.map.proto.REL_POSITION\"\xd6\x01\n\x08Junction\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.apollo.common.Header\x12\n\n\x02id\x18\x02 \x01(\x04\x12\x31\n\x05point\x18\x03 \x03(\x0b\x32\".omnisense.drivers.seyond.PointENU\x12\x37\n\x0bjoin_points\x18\x04 \x03(\x0b\x32\".omnisense.map.proto.JoinPointPair\x12+\n\x04mode\x18\x05 \x01(\x0e\x32\x1d.omnisense.map.proto.JOINMODE*#\n\x0cREL_POSITION\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01*h\n\x08JOINMODE\x12\x08\n\x04\x46ORK\x10\x00\x12\t\n\x05MERGE\x10\x01\x12\t\n\x05\x43ROSS\x10\x02\x12\x0b\n\x07UNKNOWN\x10\x03\x12\x0e\n\nLEFT_MERGE\x10\x04\x12\x0e\n\nLEFT_CROSS\x10\x05\x12\x0f\n\x0bNO_JUNCTION\x10\x06'
  ,
  dependencies=[modules_dot_common_dot_proto_dot_header__pb2.DESCRIPTOR,modules_dot_omnisense_dot_common_dot_proto_dot_pose__pb2.DESCRIPTOR,])

_REL_POSITION = _descriptor.EnumDescriptor(
  name='REL_POSITION',
  full_name='omnisense.map.proto.REL_POSITION',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=542,
  serialized_end=577,
)
_sym_db.RegisterEnumDescriptor(_REL_POSITION)

REL_POSITION = enum_type_wrapper.EnumTypeWrapper(_REL_POSITION)
_JOINMODE = _descriptor.EnumDescriptor(
  name='JOINMODE',
  full_name='omnisense.map.proto.JOINMODE',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FORK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MERGE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CROSS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEFT_MERGE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LEFT_CROSS', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='NO_JUNCTION', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=579,
  serialized_end=683,
)
_sym_db.RegisterEnumDescriptor(_JOINMODE)

JOINMODE = enum_type_wrapper.EnumTypeWrapper(_JOINMODE)
LEFT = 0
RIGHT = 1
FORK = 0
MERGE = 1
CROSS = 2
UNKNOWN = 3
LEFT_MERGE = 4
LEFT_CROSS = 5
NO_JUNCTION = 6



_JOINPOINTPAIR = _descriptor.Descriptor(
  name='JoinPointPair',
  full_name='omnisense.map.proto.JoinPointPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='near_point', full_name='omnisense.map.proto.JoinPointPair.near_point', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='far_point', full_name='omnisense.map.proto.JoinPointPair.far_point', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='omnisense.map.proto.JoinPointPair.position', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=323,
)


_JUNCTION = _descriptor.Descriptor(
  name='Junction',
  full_name='omnisense.map.proto.Junction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='omnisense.map.proto.Junction.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='omnisense.map.proto.Junction.id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='point', full_name='omnisense.map.proto.Junction.point', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='join_points', full_name='omnisense.map.proto.Junction.join_points', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='omnisense.map.proto.Junction.mode', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=540,
)

_JOINPOINTPAIR.fields_by_name['near_point'].message_type = modules_dot_omnisense_dot_common_dot_proto_dot_pose__pb2._POINTENU
_JOINPOINTPAIR.fields_by_name['far_point'].message_type = modules_dot_omnisense_dot_common_dot_proto_dot_pose__pb2._POINTENU
_JOINPOINTPAIR.fields_by_name['position'].enum_type = _REL_POSITION
_JUNCTION.fields_by_name['header'].message_type = modules_dot_common_dot_proto_dot_header__pb2._HEADER
_JUNCTION.fields_by_name['point'].message_type = modules_dot_omnisense_dot_common_dot_proto_dot_pose__pb2._POINTENU
_JUNCTION.fields_by_name['join_points'].message_type = _JOINPOINTPAIR
_JUNCTION.fields_by_name['mode'].enum_type = _JOINMODE
DESCRIPTOR.message_types_by_name['JoinPointPair'] = _JOINPOINTPAIR
DESCRIPTOR.message_types_by_name['Junction'] = _JUNCTION
DESCRIPTOR.enum_types_by_name['REL_POSITION'] = _REL_POSITION
DESCRIPTOR.enum_types_by_name['JOINMODE'] = _JOINMODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

JoinPointPair = _reflection.GeneratedProtocolMessageType('JoinPointPair', (_message.Message,), {
  'DESCRIPTOR' : _JOINPOINTPAIR,
  '__module__' : 'modules.omnisense.common.proto.map_pb2'
  # @@protoc_insertion_point(class_scope:omnisense.map.proto.JoinPointPair)
  })
_sym_db.RegisterMessage(JoinPointPair)

Junction = _reflection.GeneratedProtocolMessageType('Junction', (_message.Message,), {
  'DESCRIPTOR' : _JUNCTION,
  '__module__' : 'modules.omnisense.common.proto.map_pb2'
  # @@protoc_insertion_point(class_scope:omnisense.map.proto.Junction)
  })
_sym_db.RegisterMessage(Junction)


# @@protoc_insertion_point(module_scope)
