# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/omnisense/common/proto/mc_indicator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.common.proto import header_pb2 as modules_dot_common_dot_proto_dot_header__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/omnisense/common/proto/mc_indicator.proto',
  package='omnisense.motion_compensation',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1modules/omnisense/common/proto/mc_indicator.proto\x12\x1domnisense.motion_compensation\x1a!modules/common/proto/header.proto\"\x95\x02\n\tIndicator\x12\x14\n\x0cindicator_id\x18\x01 \x02(\x04\x12\x10\n\x08track_id\x18\x02 \x01(\x04\x12\x16\n\x0elast_frame_idx\x18\x03 \x01(\x04\x12\x15\n\rnow_frame_idx\x18\x04 \x02(\x04\x12\x12\n\nposition_y\x18\x05 \x01(\x04\x12\x12\n\nposition_z\x18\x06 \x01(\x04\x12\x10\n\x08last_v_y\x18\x07 \x01(\x04\x12\x0f\n\x07now_v_y\x18\x08 \x01(\x04\x12\x10\n\x08last_v_z\x18\t \x01(\x04\x12\x0f\n\x07now_v_z\x18\n \x01(\x04\x12\x14\n\x0clast_heading\x18\x0b \x01(\x04\x12\x13\n\x0bnow_heading\x18\x0c \x01(\x04\x12\x18\n\x10time_consumption\x18\r \x01(\x04\"I\n\nIndicators\x12;\n\tindicator\x18\x01 \x03(\x0b\x32(.omnisense.motion_compensation.Indicator'
  ,
  dependencies=[modules_dot_common_dot_proto_dot_header__pb2.DESCRIPTOR,])




_INDICATOR = _descriptor.Descriptor(
  name='Indicator',
  full_name='omnisense.motion_compensation.Indicator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='indicator_id', full_name='omnisense.motion_compensation.Indicator.indicator_id', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='track_id', full_name='omnisense.motion_compensation.Indicator.track_id', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_frame_idx', full_name='omnisense.motion_compensation.Indicator.last_frame_idx', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='now_frame_idx', full_name='omnisense.motion_compensation.Indicator.now_frame_idx', index=3,
      number=4, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_y', full_name='omnisense.motion_compensation.Indicator.position_y', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position_z', full_name='omnisense.motion_compensation.Indicator.position_z', index=5,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_v_y', full_name='omnisense.motion_compensation.Indicator.last_v_y', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='now_v_y', full_name='omnisense.motion_compensation.Indicator.now_v_y', index=7,
      number=8, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_v_z', full_name='omnisense.motion_compensation.Indicator.last_v_z', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='now_v_z', full_name='omnisense.motion_compensation.Indicator.now_v_z', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='last_heading', full_name='omnisense.motion_compensation.Indicator.last_heading', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='now_heading', full_name='omnisense.motion_compensation.Indicator.now_heading', index=11,
      number=12, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_consumption', full_name='omnisense.motion_compensation.Indicator.time_consumption', index=12,
      number=13, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=397,
)


_INDICATORS = _descriptor.Descriptor(
  name='Indicators',
  full_name='omnisense.motion_compensation.Indicators',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='indicator', full_name='omnisense.motion_compensation.Indicators.indicator', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=472,
)

_INDICATORS.fields_by_name['indicator'].message_type = _INDICATOR
DESCRIPTOR.message_types_by_name['Indicator'] = _INDICATOR
DESCRIPTOR.message_types_by_name['Indicators'] = _INDICATORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Indicator = _reflection.GeneratedProtocolMessageType('Indicator', (_message.Message,), {
  'DESCRIPTOR' : _INDICATOR,
  '__module__' : 'modules.omnisense.common.proto.mc_indicator_pb2'
  # @@protoc_insertion_point(class_scope:omnisense.motion_compensation.Indicator)
  })
_sym_db.RegisterMessage(Indicator)

Indicators = _reflection.GeneratedProtocolMessageType('Indicators', (_message.Message,), {
  'DESCRIPTOR' : _INDICATORS,
  '__module__' : 'modules.omnisense.common.proto.mc_indicator_pb2'
  # @@protoc_insertion_point(class_scope:omnisense.motion_compensation.Indicators)
  })
_sym_db.RegisterMessage(Indicators)


# @@protoc_insertion_point(module_scope)
